import { format } from 'date-fns';
import type { Invoice } from '../types/billing';
import { formatCurrency } from '../utils/proration';

interface InvoicePreviewProps {
  invoice: Invoice | null;
  companyName?: string;
}

export function InvoicePreview({ invoice, companyName = 'Your Company' }: InvoicePreviewProps) {
  if (!invoice) {
    return (
      <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Invoice Preview</h3>
        <div className="text-center py-8 text-gray-500">
          Configure your billing details to see the invoice preview
        </div>
      </div>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-gray-800 to-gray-900 text-white p-6">
        <div className="flex justify-between items-start">
          <div>
            <h2 className="text-2xl font-bold">{companyName}</h2>
            <p className="text-gray-300 text-sm mt-1">Proration Invoice</p>
          </div>
          <div className="text-right">
            <div className="text-sm text-gray-300">Invoice Date</div>
            <div className="font-semibold">{format(new Date(), 'MMM d, yyyy')}</div>
          </div>
        </div>
      </div>

      {/* Billing Period */}
      <div className="px-6 py-4 bg-gray-50 border-b border-gray-200">
        <div className="text-sm text-gray-600">
          Billing Period: <span className="font-medium text-gray-900">
            {format(invoice.periodStart, 'MMM d, yyyy')} - {format(invoice.periodEnd, 'MMM d, yyyy')}
          </span>
        </div>
      </div>

      {/* Line Items */}
      <div className="p-6">
        <table className="w-full">
          <thead>
            <tr className="text-left text-sm text-gray-500 border-b border-gray-200">
              <th className="pb-3 font-medium">Description</th>
              <th className="pb-3 font-medium text-right">Qty</th>
              <th className="pb-3 font-medium text-right">Unit Price</th>
              <th className="pb-3 font-medium text-right">Amount</th>
            </tr>
          </thead>
          <tbody>
            {invoice.lines.map((line, index) => (
              <tr key={index} className="border-b border-gray-100 last:border-0">
                <td className="py-4">
                  <div className={`font-medium ${line.isCredit ? 'text-green-700' : 'text-gray-900'}`}>
                    {line.description}
                  </div>
                </td>
                <td className="py-4 text-right text-gray-600">{line.quantity}</td>
                <td className={`py-4 text-right ${line.isCredit ? 'text-green-600' : 'text-gray-600'}`}>
                  {formatCurrency(line.unitPrice)}
                </td>
                <td className={`py-4 text-right font-medium ${line.isCredit ? 'text-green-600' : 'text-gray-900'}`}>
                  {formatCurrency(line.amount)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Totals */}
        <div className="mt-6 pt-4 border-t border-gray-200">
          <div className="flex justify-end">
            <div className="w-64 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-gray-600">Subtotal</span>
                <span className="font-medium">{formatCurrency(invoice.subtotal)}</span>
              </div>
              {invoice.credits > 0 && (
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Credits Applied</span>
                  <span className="font-medium text-green-600">-{formatCurrency(invoice.credits)}</span>
                </div>
              )}
              <div className="flex justify-between text-lg pt-2 border-t border-gray-200">
                <span className="font-semibold text-gray-900">Total</span>
                <span className={`font-bold ${invoice.total >= 0 ? 'text-gray-900' : 'text-green-600'}`}>
                  {invoice.total >= 0 ? formatCurrency(invoice.total) : `(${formatCurrency(Math.abs(invoice.total))})`}
                </span>
              </div>
              {invoice.total < 0 && (
                <div className="text-xs text-green-600 text-right">
                  Credit to be applied to next invoice
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 flex justify-between items-center">
        <div className="text-xs text-gray-500">
          Generated by ProrateMate
        </div>
        <button
          onClick={handlePrint}
          className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors print:hidden"
        >
          Print Invoice
        </button>
      </div>
    </div>
  );
}
